### ISSUE TITLE
Looking for examples

### ISSUE THREAD

**Issue by temcdrm** [GMLC-TDC/helics-ns3#35]
I found various cc and h files in the repository, but I'm not sure exactly how to build them, or what to do afterwards.  Can you please point me to an example that runs under HELICS?

**Comment by nightlark** [comment]
The examples folder has two examples of ns3 federated that run with HELICS controlling the ns3 simulation time and exchanging data.

The [installation section of the README](https://github.com/GMLC-TDC/helics-ns3/blob/master/README.md#installation) has the options and commands used to build examples.

**Comment by nightlark** [comment]
The two examples (filter and sndrcv) each have two federates, one using ns3 and the other intended to send data over the ns3 simulated network. To run it, launch a helics broker and then run a copy of the two federates for one of the examples (eg ns3-filter and  fed-filter).

**Comment by trevorhardy** [comment]
Closing due to apparent resolution and lack of activity.

**Comment by temcdrm** [comment]
We were able to make progress using newer documentation and in a newer version of HELICS.

**Comment by trevorhardy** [comment]
Are those examples publicly available such that we could link to them here?
